version: 2

builds:
  - id: yaak-cli
    binary: yaakcli
    main: ./cmd/yaakcli/main.go
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_arm64
      - darwin_amd64
      - linux_arm64
      - linux_amd64
      - windows_amd64
      - windows_arm64
