version: 2

builds:
  - id: yaak-cli
    binary: yaakcli
    main: ./cmd/yaakcli/main.go
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_arm64_v8.0
      - darwin_amd64_v1
      - linux_arm64_v8.0
      - linux_amd64_v1
      - windows_amd64_v1
