name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: macos-latest
    name: Release
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: node npm/prepare-publish.js
        env:
          YAAK_CLI_VERSION: ${{ github.ref_name }}

      - name: Publish @yaakapp/cli-darwin-arm64
        run: npm publish --provenance --access public
        working-directory: npm/cli-darwin-arm64
        env: { NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}" }

      - name: Publish @yaakapp/cli-darwin-x64
        run: npm publish --provenance --access public
        working-directory: npm/cli-darwin-x64
        env: { NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}" }

      - name: Publish @yaakapp/cli-linux-x64
        run: npm publish --provenance --access public
        working-directory: npm/cli-linux-x64
        env: { NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}" }

      - name: Publish @yaakapp/cli-win32-x64
        run: npm publish --provenance --access public
        working-directory: npm/cli-win32-x64
        env: { NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}" }

      - name: Publish @yaakapp/cli
        run: npm publish --provenance --access public
        working-directory: npm/cli
        env: { NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}" }
